#pragma once
#include "GameObject.h"
#include "ObserverComponent.h"
#include "SubjectComponent.h"
#include "TextRenderComponent.h"
#include "TextureRenderComponent.h"
#include "TimeComponent.h"
#include "TransformComponent.h"
#include "Transform.h"